[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "potato misery dry laptop tray pause diet release cage scatter grape unable time poverty earth share miss hill brisk lens dress receive tortoise sugar"
